INFERANALYZE = '/opt/infer-linux64-v0.14.0/infer/bin/infer-analyze' --no-report --results-dir '/opt/infer-linux64-v0.14.0/infer_test/examples/infer-out' 

CLUSTERS=

default: test

all: test

test: $(CLUSTERS)
	@echo


clean:
	rm -f $(CLUSTERS)
